# Generated by Django 3.1.7 on 2021-05-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpoint',
            name='post_header',
            field=models.CharField(default='Название', max_length=250, verbose_name='Название пункта'),
        ),
    ]
